### ISSUE TITLE
The project was created from scratch. But it doesn't build. 

### ISSUE THREAD

**Issue by Sabrak** [ceylon/ceylon-gradle-android#10]
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugCeylonWithCeylonc
Forced update, no checks were made, publishing...
Published module android/25 to repository path_to_project/CeylonDemo/app/build/intermediates/ceylon-android/repository.
Forced update, no checks were made, publishing...
Published module com.android.support.support-annotations/25.3.1 to repository path_to_project/CeylonDemo/app/build/intermediates/ceylon-android/repository.

ceylon import-jar: Jar file
path_to_project/CeylonDemo/app/build/intermediates/exploded-aar/com.
android.support/support-compat/25.3.1/jars/classes.jar does not exist

:app:compileDebugCeylonWithCeylonc FAILED

Android Studio 2.3.1
Ceylon 1.3.2
Gradle plugin 1.0.1
OSX 10.12.4
Support libraries 25.3.1
Compile sdk version 25
Build tools version 25.0.2

**Comment by FroMage** [comment]
Thanks for reporting.

**Comment by Sabrak** [comment]
In continue.
If manually copy all files and after start a build. We will have another error:

:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugCeylonWithCeylonc
Note: Created module com.rti.ceylondemo/1.0

path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/modules/com/rti/ceylondemo/1.0/com.rti.ceylondemo-1.0.car
/opt/ceylon-1.3.2/repo/ceylon/language/1.3.2/ceylon.language-1.3.2.car
/opt/ceylon-1.3.2/repo/com/redhat/ceylon/common/1.3.2/com.redhat.ceylon.common-1.3.2.jar
/opt/ceylon-1.3.2/repo/com/redhat/ceylon/model/1.3.2/com.redhat.ceylon.model-1.3.2.jar
/opt/ceylon-1.3.2/repo/com/redhat/ceylon/langtools/classfile/1.3.2/com.redhat.ceylon.langtools.classfile-1.3.2.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/android/25/android-25.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/appcompat-v7/25.3.1/com.android.support.appcompat-v7-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-annotations/25.3.1/com.android.support.support-annotations-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-v4/25.3.1/com.android.support.support-v4-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-fragment/25.3.1/com.android.support.support-fragment-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-core-utils/25.3.1/com.android.support.support-core-utils-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-compat/25.3.1/com.android.support.support-compat-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-core-ui/25.3.1/com.android.support.support-core-ui-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-media-compat/25.3.1/com.android.support.support-media-compat-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/support-vector-drawable/25.3.1/com.android.support.support-vector-drawable-25.3.1.jar
path_to_project/Projects/CeylonDemo/app/build/intermediates/ceylon-android/repository/com/android/support/animated-vector-drawable/25.3.1/com.android.support.animated-vector-drawable-25.3.1.jar
:app:compileDebugCeylonWithCeylonc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugCeylonWithCeylonc'.
> No such property: jarDependencies for class: com.android.build.gradle.internal.dependency.DependencyContainerImpl
  Possible solutions: allDependencies
 
android gradle plugin 2.3.1

**Comment by Sabrak** [comment]
with --stacktrace

`* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugCeylonWithCeylonc'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: groovy.lang.MissingPropertyException: No such property: jarDependencies for class: com.android.build.gradle.internal.dependency.DependencyContainerImpl
Possible solutions: allDependencies
	at com.redhat.ceylon.gradle.android.MyCeylonCompileTask$_addMlibJarsToDex_closure6.doCall(MyCeylonCompileTask.groovy:171)
	at com.redhat.ceylon.gradle.android.MyCeylonCompileTask.addMlibJarsToDex(MyCeylonCompileTask.groovy:157)
	at com.redhat.ceylon.gradle.android.MyCeylonCompileTask$addMlibJarsToDex$5.callCurrent(Unknown Source)
	at com.redhat.ceylon.gradle.android.MyCeylonCompileTask.compile(MyCeylonCompileTask.groovy:117)
	at com.redhat.ceylon.gradle.android.CeylonAndroidPlugin$_processVariantData_closure3$_closure6.doCall(CeylonAndroidPlugin.groovy:186)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more
`
